import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/nprogress/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import "@/global/configurations/mongoose";
import "@/global/configurations/cloudinary";
import "@/global/configurations/nodemailer";
import "@/global/configurations/redis";
import { inter } from "@/global/styles/fonts.style";
import { Providers } from "@/global/components/common/client";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";

export const metadata: Metadata = {
  title: "Test App",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "48x48", type: "image/x-icon" },
      { url: "/favicon.svg", sizes: "any", type: "image/svg+xml" },
    ],
    apple: "/apple-touch-icon-180x180.png",
  },
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function Layout({ children }: RootLayoutProps) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>

      <body className={`${inter.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
