import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/nprogress/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import "@/global/configurations/mongoose";
import "@/global/configurations/cloudinary";
import "@/global/configurations/nodemailer";
import { inter } from "@/global/styles/fonts.style";
import { Providers } from "@/global/components/common/client";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
// import { GetSession } from "@/features/user/queries/server";

export const metadata: Metadata = {
  title: "Test App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function Layout({ children }: RootLayoutProps) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>

      <body className={`${inter.className} antialiased`}>
        <Providers>{children}</Providers>
        {/* <GetSession>
          {(session) => <Providers session={session}>{children}</Providers>}
        </GetSession> */}
      </body>
    </html>
  );
}
